import gym
import gym_pcgrl

### sample input to be generated by matt/zubin
from sample_visualization import tile_change
tracking = tile_change

# training time vs level success (1) [todo]

# generate avg % tile-change number (2)
# generate matplotlib per agent[zelda-wide-v0, zelda-narrow-v0...], x=change_percentage,y=avg%tile_change (2)
import matplotlib.pyplot as plt
import numpy as np
ys = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
for agent in agents: 
  base = tracking[agent]
  result = [elem['tile_change_actions'] for elem in base]
  print('average % tile-change number for ' + agent + ': ', np.mean(result)) # (1)
  plt.plot(ys,result, label=agent)
  plt.legend(loc="upper left")

plt.title("change % vs # tile change actions")
plt.xlabel("change_percentage")
plt.ylabel("tile change actions")
plt.savefig('tileactions_vs_changepercentage.png') # (2)
plt.close()